apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-deployment
  labels:
    component: auth
spec:
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      component: auth
  template:
    metadata:
      labels:
        component: auth
    spec:
      containers:
        - name: auth-deployment
          image: jacknguyenvan/nestjs-rabbitmq-microservices-auth
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: '3001'
            - name: JWT_EXPIRATION
              value: '3600'
            - name: JWT_SECRET
              value: yJSDVpxKUQ1LSfrnrsLN6r6tmFd1i95I3zGXjpIryO8zoWg7fDmYEnyyCmtKFh2MFd4c7rFjN9wKsiwRXYKZ9BKJ5YHTByQi8Q4
            - name: MONGODB_URI
              value: mongodb://mongodb-primary:27017/
            - name: RABBIT_MQ_URI
              value: amqp://rabbitmq:5672
            - name: RABBIT_MQ_AUTH_QUEUE
              value: auth
---
apiVersion: v1
kind: Service
metadata:
  name: auth-service
  labels:
    component: auth
spec:
  type: NodePort
  selector:
    component: auth
  ports:
    - protocol: TCP
      port: 3001
      targetPort: 3001
      nodePort: 30010
