apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
spec:
  strategy:
    type: Recreate
  selector:
    matchLabels:
      component: rabbitmq
  template:
    metadata:
      labels:
        component: rabbitmq
    spec:
      containers:
        - name: rabbitmq
          image: rabbitmq
          ports:
            - containerPort: 5672
---
apiVersion: v1
kind: Service
metadata:
  name: rabbitmq
  labels:
    component: rabbitmq
spec:
  selector:
    component: rabbitmq
  ports:
    - port: 5672
